### ISSUE TITLE
emulate a SuperScope (feat. request)

### ISSUE THREAD

**Issue by eadmaster** [charasyn/ps2tosnes#2]
I am not sure if this is doable, btw it could be a nice solution for the well-know issue of the SuperScope not working on LCD displays.

**Comment by charasyn** [comment]
It should be easy enough to add support for the controller, but making it work in a logical way might be harder. I'll start looking into the Super Scope.

**Comment by charasyn** [comment]
Okay, I have looked into how the Super Scope works, and I don't believe there is a way to make this project emulate a Super Scope. Sorry. If anyone reading this understands the Super Scope and has an idea as to how to make it work, feel free to open a new issue.
