### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by lacrima08** [charasyn/ps2tosnes#5]
Hi,

I made the assembly and used an old PS/2 optical mouse with 2 buttons and a scroll wheel. However, the left and right buttons are inverted.

Any ideas, please?

Do I need to edit the part of code ?

  #ifdef REVERSE_BUTTONS
  bitout[8]=mdata[0]&0x01?0:1;
  bitout[9]=mdata[0]&0x02?0:1;
  #else
  bitout[8]=mdata[0]&0x02?0:1;
  bitout[9]=mdata[0]&0x01?0:1;
  #endif

Regards,

**Comment by charasyn** [comment]
On line 40, it says `#define REVERSE_BUTTONS` - try commenting out this line.

**Comment by lacrima08** [comment]
> On line 40, it says `#define REVERSE_BUTTONS` - try commenting out this line.

Thanks! I'll give it a try.

**Comment by lacrima08** [comment]
It works like a charm ! Thank You !
