### ISSUE TITLE
Question about USB Mouse

### ISSUE THREAD

**Issue by lacrima08** [charasyn/ps2tosnes#6]
Hi,

Working perfectly with a PS/2 optical mouse and after editing line 40 to invert left and right buttons, I 've now an another question.

I tried too with and USB Optical Mouse with an USB to PS/2 adaptor, the optical signal is OK but can't move or click.

is there any way to use a usb mouse with a usb to ps/2 adapter like this : 

![61rWMwRFpVL _AC_SL1500_](https://github.com/user-attachments/assets/6b89b19c-40c0-44c5-8e20-e45652df4eb1)

Maybe with a different type of wiring?

I tested continuity with a multimeter, and it looks good compared to the wiring diagrams for the usb and ps/2 ports.

Sorry for the potentially stupid question, but my knowledge of electronics is poor.

**Comment by charasyn** [comment]
No worries :)
These converters are completely passive, meaning that the mouse itself needs to support both USB and PS/2 protocols, and needs to automatically detect which one to use. Can you test this mouse on a PC with a PS/2 port to ensure the mouse works with PS/2? Usually modern mice don't support PS/2.

**Comment by lacrima08** [comment]
indeed, it doesn't work with the adapter on my pc, but works with usb. So I need to find compatible usb mice, in case my old ps/2 mouse stops working one day.

Thank you for your reply !
